/** Catalog of fields for Accident forms — L1 wizard steps, L2 collapsible groups, L3 leaves. */

export const ACCIDENT_FORM_SECTIONS = [
  {
    id: "basics",
    label: "Incident basics",
    description: "Vehicle, date/time, driver, location, and description of the accident.",
    columns: 1,
  },
  {
    id: "circumstances",
    label: "Circumstances",
    description: "Use of vehicle, further details, fault, and police reporting.",
    columns: 1,
  },
  {
    id: "damage",
    label: "Damage and parties",
    description: "Vehicle damage, third-party vehicles, and property damage.",
    columns: 1,
  },
  {
    id: "people",
    label: "People and other",
    description: "Injuries, witnesses, comments, and photo attachments.",
    columns: 1,
  },
];

/** Collapsible subfolders under each Level-1 wizard step. */
export const ACCIDENT_FORM_GROUPS = [
  // —— Incident basics ——
  {
    id: "vehicle",
    sectionId: "basics",
    label: "Vehicle details",
    description: "Select the vehicle and its current location.",
    columns: 1,
  },
  {
    id: "datetime",
    sectionId: "basics",
    label: "Date and time of accident",
    description: "When the accident took place.",
    columns: 2,
  },
  {
    id: "driver",
    sectionId: "basics",
    label: "Driver details",
    description: "Resolved from the vehicle assignment at the accident date and time.",
    columns: 1,
  },
  {
    id: "location",
    sectionId: "basics",
    label: "Location",
    description: "Where the accident occurred.",
    columns: 1,
  },
  {
    id: "description",
    sectionId: "basics",
    label: "Description of accident",
    description: "Select the accident type and describe what happened.",
    columns: 1,
  },

  // —— Circumstances ——
  {
    id: "useOfVehicle",
    sectionId: "circumstances",
    label: "Use of vehicle",
    description: "How the vehicle was being used at the time of the accident.",
    columns: 2,
  },
  {
    id: "furtherDetails",
    sectionId: "circumstances",
    label: "Further details of accident",
    description: "Speed, horn, lamps, and related details.",
    columns: 2,
  },
  {
    id: "fault",
    sectionId: "circumstances",
    label: "Fault",
    description: "Who you believe was to blame for the accident.",
    columns: 2,
  },
  {
    id: "police",
    sectionId: "circumstances",
    label: "Police reporting",
    description: "Whether the accident was reported to the police.",
    columns: 2,
  },

  // —— Damage and parties ——
  {
    id: "damage",
    sectionId: "damage",
    label: "Damage to vehicle",
    description: "General damage statement and affected vehicle components.",
    columns: 1,
  },
  {
    id: "thirdPartyVehicles",
    sectionId: "damage",
    label: "Third party vehicle involvement",
    description: "Other vehicles involved in the accident.",
    columns: 2,
  },
  {
    id: "thirdPartyProperty",
    sectionId: "damage",
    label: "Third party property damage",
    description: "Damage to property that does not belong to the fleet.",
    columns: 2,
  },

  // —— People and other ——
  {
    id: "injuries",
    sectionId: "people",
    label: "Injuries",
    description: "Injured persons, their role, and type of injury.",
    columns: 2,
  },
  {
    id: "witnesses",
    sectionId: "people",
    label: "Witnesses",
    description: "Optional. Add anyone who witnessed the accident.",
    columns: 2,
  },
  {
    id: "other",
    sectionId: "people",
    label: "Other information",
    description: "General comments, additional questions, and photo attachments.",
    columns: 1,
  },
];

const HALF = 1;
const FULL = 2;
const FULL_1 = 1; // full width in a 1-column section

export const ACCIDENT_FORM_FIELD_CATALOG = [
  // —— Vehicle details ——
  {
    id: "acc_vehicle",
    key: "vehicleId",
    title: "Vehicle",
    fieldType: "vehicle",
    sectionId: "basics",
    groupId: "vehicle",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Select vehicle…",
  },
  {
    id: "acc_vehicle_location",
    key: "vehicleCurrentLocation",
    title: "Current location of vehicle",
    fieldType: "location",
    sectionId: "basics",
    groupId: "vehicle",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Search location, click the map, or use GPS",
  },

  // —— Date / time ——
  {
    id: "acc_incident_date",
    key: "incidentDate",
    title: "Date",
    fieldType: "date",
    sectionId: "basics",
    groupId: "datetime",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_incident_time",
    key: "incidentTime",
    title: "Time",
    fieldType: "time",
    sectionId: "basics",
    groupId: "datetime",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },

  // —— Driver ——
  {
    id: "acc_driver_bypass",
    key: "driverBypass",
    title: "No driver was in charge or involved",
    fieldType: "checkbox",
    sectionId: "basics",
    groupId: "driver",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
  },
  {
    id: "acc_driver",
    key: "driverId",
    title: "Driver",
    fieldType: "driver",
    sectionId: "basics",
    groupId: "driver",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Search driver…",
  },

  // —— Location ——
  {
    id: "acc_accident_location",
    key: "accidentLocation",
    title: "Location of accident",
    fieldType: "location",
    sectionId: "basics",
    groupId: "location",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Search location, click the map, or use GPS",
  },

  // —— Description ——
  {
    id: "acc_accident_type",
    key: "accidentType",
    title: "Type of accident",
    fieldType: "select",
    sectionId: "basics",
    groupId: "description",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Select type…",
    options: [
      { value: "COLLISION", label: "Collision" },
      { value: "REAR_END", label: "Rear-end" },
      { value: "SIDE_SWIPE", label: "Side swipe" },
      { value: "ROLLOVER", label: "Rollover" },
      { value: "HIT_PEDESTRIAN", label: "Hit pedestrian" },
      { value: "HIT_PROPERTY", label: "Hit property" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    id: "acc_what_happened",
    key: "whatHappened",
    title: "Describe what happened",
    fieldType: "textarea",
    sectionId: "basics",
    groupId: "description",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Describe the accident…",
  },

  // —— Use of vehicle (questionnaire leaves) ——
  {
    id: "acc_vehicle_purpose",
    key: "vehiclePurpose",
    title: "For what purpose was the vehicle being used?",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "useOfVehicle",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_had_permission",
    key: "hadPermission",
    title: "Did the user have permission?",
    fieldType: "yes_no",
    sectionId: "circumstances",
    groupId: "useOfVehicle",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_goods_carried",
    key: "goodsCarried",
    title: "Were goods or samples being carried?",
    fieldType: "yes_no",
    sectionId: "circumstances",
    groupId: "useOfVehicle",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_unloaded_weight",
    key: "unloadedWeight",
    title: "Unloaded weight",
    fieldType: "number",
    sectionId: "circumstances",
    groupId: "useOfVehicle",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_carrying_capacity",
    key: "carryingCapacity",
    title: "Carrying capacity",
    fieldType: "number",
    sectionId: "circumstances",
    groupId: "useOfVehicle",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_weight_of_load",
    key: "weightOfLoad",
    title: "Weight of load",
    fieldType: "number",
    sectionId: "circumstances",
    groupId: "useOfVehicle",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },

  // —— Further details ——
  {
    id: "acc_vehicle_speed",
    key: "vehicleSpeed",
    title: "Speed of vehicle",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "furtherDetails",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_lamps_hit",
    key: "lampsHit",
    title: "Which lamps of your vehicle were hit?",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "furtherDetails",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_horn_sounded",
    key: "hornSounded",
    title: "Was the horn sounded?",
    fieldType: "yes_no",
    sectionId: "circumstances",
    groupId: "furtherDetails",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },

  // —— Fault ——
  {
    id: "acc_driver_to_blame",
    key: "driverToBlame",
    title: "Do you think the driver was to blame?",
    fieldType: "yes_no",
    sectionId: "circumstances",
    groupId: "fault",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_other_person_to_blame",
    key: "otherPersonToBlame",
    title: "Was some other person to blame?",
    fieldType: "yes_no",
    sectionId: "circumstances",
    groupId: "fault",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_other_person_name",
    key: "otherPersonName",
    title: "Name of other person",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "fault",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_other_person_address",
    key: "otherPersonAddress",
    title: "Address",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "fault",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_other_person_phone",
    key: "otherPersonPhone",
    title: "Phone number",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "fault",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_other_person_id",
    key: "otherPersonId",
    title: "ID number",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "fault",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },

  // —— Police ——
  {
    id: "acc_police_reported",
    key: "police.reported",
    title: "Has the accident been reported to the police?",
    fieldType: "yes_no",
    sectionId: "circumstances",
    groupId: "police",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_police_station_name",
    key: "police.stationName",
    title: "Police station name",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "police",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_police_station_location",
    key: "police.stationLocation",
    title: "Police station location",
    fieldType: "text",
    sectionId: "circumstances",
    groupId: "police",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_police_signed",
    key: "police.signedStatement",
    title: "Did you give a signed statement / evidence?",
    fieldType: "yes_no",
    sectionId: "circumstances",
    groupId: "police",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_police_evidence",
    key: "police.evidenceNotes",
    title: "Evidence / statement notes",
    fieldType: "textarea",
    sectionId: "circumstances",
    groupId: "police",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },

  // —— Damage to vehicle ——
  {
    id: "acc_vehicle_damage_answer",
    key: "vehicleDamageAnswer",
    title: "Was there damage to the vehicle?",
    fieldType: "yes_no",
    sectionId: "damage",
    groupId: "damage",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
  },
  {
    id: "acc_vehicle_damage_statement",
    key: "vehicleDamageStatement",
    title: "General statement of damage",
    fieldType: "textarea",
    sectionId: "damage",
    groupId: "damage",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
  },
  {
    id: "acc_damage_lines",
    key: "damageLines",
    title: "Vehicle damage details",
    fieldType: "damage_lines",
    sectionId: "damage",
    groupId: "damage",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
  },

  // —— Third party vehicles ——
  {
    id: "acc_tp_vehicles_answer",
    key: "thirdPartyVehiclesAnswer",
    title: "Was a third party vehicle involved?",
    fieldType: "yes_no",
    sectionId: "damage",
    groupId: "thirdPartyVehicles",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_tp_vehicles_list",
    key: "thirdPartyVehicles",
    title: "Third party vehicles",
    fieldType: "repeatable",
    sectionId: "damage",
    groupId: "thirdPartyVehicles",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },

  // —— Third party property ——
  {
    id: "acc_tp_property_answer",
    key: "thirdPartyPropertyAnswer",
    title: "Was there any damage to third party property?",
    fieldType: "yes_no",
    sectionId: "damage",
    groupId: "thirdPartyProperty",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_tp_property_type",
    key: "thirdPartyProperty.propertyType",
    title: "Type of property",
    fieldType: "select",
    sectionId: "damage",
    groupId: "thirdPartyProperty",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
    options: [
      { value: "BUILDING", label: "Building" },
      { value: "FENCE", label: "Fence / wall" },
      { value: "STREET_FURNITURE", label: "Street furniture" },
      { value: "CROP_LAND", label: "Crop / land" },
      { value: "OTHER", label: "Other" },
    ],
  },
  {
    id: "acc_tp_owner_name",
    key: "thirdPartyProperty.ownerName",
    title: "Owner name",
    fieldType: "text",
    sectionId: "damage",
    groupId: "thirdPartyProperty",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_tp_owner_phone",
    key: "thirdPartyProperty.ownerPhone",
    title: "Owner phone",
    fieldType: "text",
    sectionId: "damage",
    groupId: "thirdPartyProperty",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_tp_owner_id",
    key: "thirdPartyProperty.ownerId",
    title: "Owner ID",
    fieldType: "text",
    sectionId: "damage",
    groupId: "thirdPartyProperty",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_tp_owner_address",
    key: "thirdPartyProperty.ownerAddress",
    title: "Owner address",
    fieldType: "text",
    sectionId: "damage",
    groupId: "thirdPartyProperty",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "acc_tp_property_description",
    key: "thirdPartyProperty.description",
    title: "Describe the property and damage",
    fieldType: "textarea",
    sectionId: "damage",
    groupId: "thirdPartyProperty",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },

  // —— Injuries ——
  {
    id: "acc_injuries_answer",
    key: "injuriesAnswer",
    title: "Were there any injuries?",
    fieldType: "yes_no",
    sectionId: "people",
    groupId: "injuries",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },
  {
    id: "acc_injuries_list",
    key: "injuries",
    title: "Injured persons",
    fieldType: "repeatable",
    sectionId: "people",
    groupId: "injuries",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },

  // —— Witnesses ——
  {
    id: "acc_witnesses_list",
    key: "witnesses",
    title: "Witnesses",
    fieldType: "repeatable",
    sectionId: "people",
    groupId: "witnesses",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
  },

  // —— Other ——
  {
    id: "acc_general_comments",
    key: "generalComments",
    title: "General comments",
    fieldType: "textarea",
    sectionId: "people",
    groupId: "other",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
  },
  {
    id: "acc_additional_notes",
    key: "additionalNotes",
    title: "Anything else that may help the investigation?",
    fieldType: "text",
    sectionId: "people",
    groupId: "other",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
  },
  {
    id: "acc_photos",
    key: "photos",
    title: "Upload photos",
    fieldType: "file",
    sectionId: "people",
    groupId: "other",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    acceptedFileTypes: ["image", "pdf", "word"],
  },
];

export const DEFAULT_VISIBLE_FIELD_IDS_BY_SECTION = Object.fromEntries(
  ACCIDENT_FORM_SECTIONS.map((section) => [
    section.id,
    ACCIDENT_FORM_FIELD_CATALOG.filter((field) => field.sectionId === section.id).map(
      (field) => field.id,
    ),
  ]),
);

export const LOCKED_DEFAULT_FIELD_IDS_BY_SECTION = Object.fromEntries(
  ACCIDENT_FORM_SECTIONS.map((section) => [
    section.id,
    ACCIDENT_FORM_FIELD_CATALOG.filter(
      (field) => field.sectionId === section.id && field.isDefaultLocked === true,
    ).map((field) => field.id),
  ]),
);

export function getLockedDefaultFieldIds(sectionId) {
  return LOCKED_DEFAULT_FIELD_IDS_BY_SECTION[sectionId] ?? [];
}

export function withLockedDefaultFields(visibleBySection = {}) {
  const next = { ...visibleBySection };
  for (const section of ACCIDENT_FORM_SECTIONS) {
    const locked = getLockedDefaultFieldIds(section.id);
    const current = new Set(next[section.id] ?? []);
    locked.forEach((id) => current.add(id));
    next[section.id] = [...current];
  }
  return next;
}
