/** Catalog of fields for New Quotation forms — fixed L1 wizard steps with leaf fields. */

export const QUOTATION_FORM_SECTIONS = [
  {
    id: "initial_details",
    label: "Initial Details",
    description: "Quote scope, risk class, vehicle values, cover type, and duration.",
    columns: 2,
  },
  {
    id: "compare_quotes",
    label: "Compare Quotes",
    description: "Review insurer quotes. Adjust opens additional benefits, then revise.",
    columns: 1,
  },
  {
    id: "additional_details",
    label: "Additional Details",
    description: "Company and vehicle registration details for the selected policy.",
    columns: 2,
  },
  {
    id: "purchase",
    label: "Purchase",
    description: "Pay with Mobile Money, bank transfer, or cheque.",
    columns: 1,
  },
];

/** Additional benefits adjust modal — configured as its own tree section in Forms setup. */
export const QUOTATION_ADJUST_SECTION = {
  id: "additional_benefits",
  label: "Additional Benefits",
  description: "Buy excess buy-back, extra TPPDL, and PA benefit before revising quotes.",
  columns: 1,
};

const HALF = 1;
const FULL_2 = 2;
const FULL_1 = 1;

/** Official risk classes for New Quotation / Dropdown Options. */
export const DEFAULT_RISK_CLASS_OPTIONS = [
  { value: "motor_cycle", label: "MOTOR CYCLE" },
  { value: "trade_plate_class_3_gw1", label: "TRADE PLATE – CLASS 3 GW.1" },
  { value: "trade_plate_class_2_gw1", label: "TRADE PLATE – CLASS 2 GW.1" },
  { value: "general_cartage", label: "GENERAL CARTAGE" },
  { value: "own_goods_carrying", label: "OWN GOODS CARRYING" },
  { value: "special_type_on_site_z801", label: "SPECIAL TYPE – ON SITE Z.801" },
  { value: "special_type_on_road_z802", label: "SPECIAL TYPE – ON ROAD Z.802" },
  { value: "trade_plate_class_1_gw1", label: "TRADE PLATE – CLASS 1 GW.1" },
  { value: "ambulance_hearse", label: "AMBULANCE / HEARSE" },
  { value: "x1_private_individual", label: "X.1 (private individual)" },
  { value: "taxi", label: "TAXI" },
  { value: "hiring_cars", label: "HIRING CARS" },
  { value: "mini_bus", label: "MINI BUS" },
  { value: "x4_private_corporate", label: "X.4 (private corporate)" },
  { value: "maxi_bus", label: "MAXI BUS" },
  { value: "articulator_tankers", label: "ARTICULATOR / TANKERS" },
];

export const QUOTATION_FORM_FIELD_CATALOG = [
  // —— Initial Details ——
  {
    id: "quot_scope",
    key: "scope",
    title: "Single or Fleet",
    fieldType: "radio",
    sectionId: "initial_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_2,
    defaultValue: "single",
    options: [
      { value: "single", label: "Single" },
      { value: "fleet", label: "Fleet" },
    ],
    description: "Fleet opens a table to collect multiple vehicle requests.",
  },
  {
    id: "quot_risk_class",
    key: "riskClass",
    title: "Risk Class",
    fieldType: "select",
    sectionId: "initial_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Select risk class…",
    options: DEFAULT_RISK_CLASS_OPTIONS,
    description: "Values also live under Dropdown Options → Risk Class.",
  },
  {
    id: "quot_seats",
    key: "seats",
    title: "Number of Seats",
    fieldType: "number",
    sectionId: "initial_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    defaultValue: "5",
    placeholder: "e.g. 5",
  },
  {
    id: "quot_currency",
    key: "currency",
    title: "Currency",
    fieldType: "select",
    sectionId: "initial_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    defaultValue: "GHS",
    options: [
      { value: "GHS", label: "GHS (GH₵)" },
      { value: "USD", label: "USD" },
      { value: "EUR", label: "EUR" },
    ],
  },
  {
    id: "quot_vehicle_value",
    key: "vehicleValue",
    title: "Value of Vehicle",
    fieldType: "text",
    sectionId: "initial_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. 185,000",
  },
  {
    id: "quot_accessories_value",
    key: "accessoriesValue",
    title: "Value of Accessories",
    fieldType: "text",
    sectionId: "initial_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. 5,000",
  },
  {
    id: "quot_cover_type",
    key: "coverType",
    title: "Type of Cover",
    fieldType: "select",
    sectionId: "initial_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_2,
    defaultValue: "Comprehensive",
    options: [
      { value: "Third Party", label: "Third Party" },
      { value: "Third Party Fire & Theft", label: "Third Party Fire & Theft" },
      { value: "Comprehensive", label: "Comprehensive" },
    ],
  },
  {
    id: "quot_months",
    key: "months",
    title: "Number of Months",
    fieldType: "number",
    sectionId: "initial_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_2,
    defaultValue: "12",
    placeholder: "e.g. 12",
  },

  // —— Compare Quotes ——
  {
    id: "quot_selected_quote",
    key: "selectedQuoteId",
    title: "Selected quote",
    fieldType: "select",
    sectionId: "compare_quotes",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Select a quote…",
    options: null,
    description: "Rendered as insurer quote cards in the New Quotation wizard.",
  },

  // —— Additional Benefits (Adjust modal tree) ——
  {
    id: "quot_excess_buyback",
    key: "excessBuyBack",
    title: "Buy Excess Buy Back",
    fieldType: "radio",
    sectionId: "additional_benefits",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    defaultValue: "no",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
  {
    id: "quot_extra_tppdl",
    key: "extraTppdl",
    title: "Buy Extra TPPDL",
    fieldType: "text",
    sectionId: "additional_benefits",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Enter amount",
  },
  {
    id: "quot_pa_benefit",
    key: "paBenefit",
    title: "Buy PA Benefit",
    fieldType: "text",
    sectionId: "additional_benefits",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "Enter amount",
  },

  // —— Additional Details ——
  {
    id: "quot_company_name",
    key: "companyName",
    title: "Company Name",
    fieldType: "text",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Auto-filled from profile",
  },
  {
    id: "quot_company_phone",
    key: "companyPhone",
    title: "Phone",
    fieldType: "text",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Auto-filled",
  },
  {
    id: "quot_company_email",
    key: "companyEmail",
    title: "Email",
    fieldType: "text",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Auto-filled",
  },
  {
    id: "quot_company_address",
    key: "companyAddress",
    title: "Address",
    fieldType: "textarea",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_2,
    placeholder: "Auto-filled",
  },
  {
    id: "quot_digital_address",
    key: "digitalAddress",
    title: "Digital Address",
    fieldType: "text",
    sectionId: "additional_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. GA-123-4567",
  },
  {
    id: "quot_reg_type",
    key: "registrationType",
    title: "Type of Vehicle Registration",
    fieldType: "select",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    options: [
      { value: "standard", label: "Standard" },
      { value: "customised", label: "Customised" },
    ],
  },
  {
    id: "quot_reg_number",
    key: "registrationNumber",
    title: "Registration Number",
    fieldType: "text",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. GR-882-20",
  },
  {
    id: "quot_make",
    key: "make",
    title: "Make",
    fieldType: "select",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Select make…",
    options: null,
  },
  {
    id: "quot_model",
    key: "model",
    title: "Model",
    fieldType: "select",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Select model…",
    options: null,
  },
  {
    id: "quot_body",
    key: "body",
    title: "Body",
    fieldType: "select",
    sectionId: "additional_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Select body…",
    options: null,
  },
  {
    id: "quot_year",
    key: "year",
    title: "Year of Manufacture",
    fieldType: "text",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. 2022",
  },
  {
    id: "quot_color",
    key: "color",
    title: "Color",
    fieldType: "text",
    sectionId: "additional_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. White",
  },
  {
    id: "quot_chassis",
    key: "chassisNumber",
    title: "Chassis Number",
    fieldType: "text",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Chassis / VIN",
  },
  {
    id: "quot_policy_start",
    key: "policyStartDate",
    title: "Policy Start Date",
    fieldType: "date",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "quot_policy_end",
    key: "policyEndDate",
    title: "Policy End Date",
    fieldType: "date",
    sectionId: "additional_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },

  // —— Purchase ——
  {
    id: "quot_payment_method",
    key: "paymentMethod",
    title: "Payment Method",
    fieldType: "select",
    sectionId: "purchase",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    defaultValue: "Mobile Money (MoMo)",
    options: [
      "Mobile Money (MoMo)",
      "Bank Transfer",
      "Cheque",
    ],
  },
  {
    id: "quot_payment_account",
    key: "paymentAccount",
    title: "Mobile Number / Account / Cheque Ref",
    fieldType: "text",
    sectionId: "purchase",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL_1,
    placeholder: "e.g. 0244 000 000",
  },
];

export const DEFAULT_VISIBLE_FIELD_IDS_BY_SECTION = Object.fromEntries(
  [...QUOTATION_FORM_SECTIONS, QUOTATION_ADJUST_SECTION].map((section) => [
    section.id,
    QUOTATION_FORM_FIELD_CATALOG.filter((field) => field.sectionId === section.id).map(
      (field) => field.id,
    ),
  ]),
);

export const LOCKED_DEFAULT_FIELD_IDS_BY_SECTION = Object.fromEntries(
  [...QUOTATION_FORM_SECTIONS, QUOTATION_ADJUST_SECTION].map((section) => [
    section.id,
    QUOTATION_FORM_FIELD_CATALOG.filter(
      (field) => field.sectionId === section.id && field.isDefaultLocked === true,
    ).map((field) => field.id),
  ]),
);

export function getLockedDefaultFieldIds(sectionId) {
  return LOCKED_DEFAULT_FIELD_IDS_BY_SECTION[sectionId] ?? [];
}

export function withLockedDefaultFields(visibleBySection = {}) {
  const next = { ...visibleBySection };
  for (const section of [...QUOTATION_FORM_SECTIONS, QUOTATION_ADJUST_SECTION]) {
    const locked = getLockedDefaultFieldIds(section.id);
    const current = new Set(next[section.id] ?? []);
    locked.forEach((id) => current.add(id));
    next[section.id] = [...current];
  }
  return next;
}
