/** Catalog of fields for Upload Vehicle Document — one Main section with insurance subfolders. */

export const VEHICLE_DOCUMENT_FORM_SECTIONS = [
  {
    id: "main_form",
    label: "Main",
    description:
      "Upload a vehicle document. Insurance Policy Details and Limits of Liability appear for Vehicle Insurance.",
    columns: 2,
  },
];

/** Collapsible subfolders under Main. */
export const VEHICLE_DOCUMENT_FORM_GROUPS = [
  {
    id: "insurance_policy_details",
    sectionId: "main_form",
    label: "Insurance Policy Details",
    description:
      "Insurer, policy numbers, premium, cover dates, and the named insured.",
    columns: 2,
  },
  {
    id: "limits_of_liability",
    sectionId: "main_form",
    label: "Limits of Liability",
    description: "Sum insured and third-party cover limits from the certificate.",
    columns: 2,
  },
];

const HALF = 1;
const FULL = 2;

export const VEHICLE_DOCUMENT_TYPES = [
  "Vehicle Registration",
  "Vehicle Insurance",
  "Roadworthiness Certificate",
  "Vehicle Inspection Report",
  "Other",
];

export const VEHICLE_DOCUMENT_INSURANCE_COMPANIES = [
  "Enterprise Insurance",
  "SIC Insurance",
  "Hollard Insurance",
  "Star Assurance",
  "GLEPA Insurance",
  "Other",
];

export const VEHICLE_DOCUMENT_CURRENCY_OPTIONS = ["GHS", "USD", "EUR", "GBP"];

export const VEHICLE_DOCUMENT_POLICY_TYPES = [
  "Comprehensive",
  "Third Party Only",
  "Third Party Fire & Theft",
];

export const VEHICLE_DOCUMENT_FORM_FIELD_CATALOG = [
  // —— Main (2 cols) ——
  {
    id: "vdf_file",
    key: "file",
    title: "Document file",
    fieldType: "file",
    sectionId: "main_form",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
    acceptedFileTypes: ["images", "pdf", "word"],
    description: "PDF, DOC, DOCX, JPG, or PNG.",
  },
  {
    id: "vdf_document_type",
    key: "documentType",
    title: "Document Type",
    fieldType: "select",
    sectionId: "main_form",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Select type…",
    options: [...VEHICLE_DOCUMENT_TYPES],
  },
  {
    id: "vdf_vehicle",
    key: "vehicleId",
    title: "Vehicle",
    fieldType: "select",
    sectionId: "main_form",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Select vehicle…",
    options: null,
    description: "Fleet vehicle this document belongs to.",
  },
  {
    id: "vdf_document_name",
    key: "docName",
    title: "Document Name",
    fieldType: "text",
    sectionId: "main_form",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. Vehicle Registration — GR-4521-21",
    minLength: 2,
    maxLength: 80,
    description: "Hidden when Document Type is Vehicle Insurance.",
  },
  {
    id: "vdf_expiry_date",
    key: "expiryDate",
    title: "Expiry Date",
    fieldType: "date",
    sectionId: "main_form",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    description: "Optional. For Vehicle Insurance this follows Policy End / Expiry Date.",
  },

  // —— Insurance Policy Details (2 cols) ——
  {
    id: "vdf_insurance_company",
    key: "insuranceCompany",
    title: "Insurance Company",
    fieldType: "select",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Select company…",
    options: [...VEHICLE_DOCUMENT_INSURANCE_COMPANIES],
  },
  {
    id: "vdf_policy_number",
    key: "policyNumber",
    title: "Policy Number",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. POL-88210",
    minLength: 3,
    maxLength: 40,
  },
  {
    id: "vdf_motor_certificate",
    key: "motorCertificateNumber",
    title: "Motor Certificate Number",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    maxLength: 40,
  },
  {
    id: "vdf_sticker_number",
    key: "stickerNumber",
    title: "Sticker Number",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    maxLength: 40,
  },
  {
    id: "vdf_policy_type",
    key: "policyType",
    title: "Type of Policy",
    fieldType: "select",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    defaultValue: "Comprehensive",
    options: [...VEHICLE_DOCUMENT_POLICY_TYPES],
  },
  {
    id: "vdf_liability_currency",
    key: "liabilityCurrency",
    title: "Currency (limits)",
    fieldType: "select",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    defaultValue: "GHS",
    options: [...VEHICLE_DOCUMENT_CURRENCY_OPTIONS],
  },
  {
    id: "vdf_premium_paid",
    key: "premiumPaid",
    title: "Premium Paid",
    fieldType: "number",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "0.00",
  },
  {
    id: "vdf_premium_currency",
    key: "premiumCurrency",
    title: "Premium Currency",
    fieldType: "select",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    defaultValue: "GHS",
    options: [...VEHICLE_DOCUMENT_CURRENCY_OPTIONS],
  },
  {
    id: "vdf_no_claim_discount",
    key: "noClaimDiscount",
    title: "No Claim Discount",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Optional",
    maxLength: 40,
  },
  {
    id: "vdf_fleet_discount",
    key: "fleetDiscount",
    title: "Fleet Discount",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Optional",
    maxLength: 40,
  },
  {
    id: "vdf_other_discounts",
    key: "otherDiscounts",
    title: "Other Discounts",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "Optional",
    maxLength: 80,
  },
  {
    id: "vdf_excess",
    key: "excessDeductible",
    title: "Excess / Deductible",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    maxLength: 40,
  },
  {
    id: "vdf_policy_start",
    key: "policyStartDate",
    title: "Policy Start Date",
    fieldType: "date",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "vdf_policy_end",
    key: "policyEndDate",
    title: "Policy End / Expiry Date",
    fieldType: "date",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
  },
  {
    id: "vdf_name_of_insured",
    key: "nameOfInsured",
    title: "Name of Insured",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
    placeholder: "As shown on the certificate or policy",
    minLength: 2,
    maxLength: 80,
  },
  {
    id: "vdf_address",
    key: "address",
    title: "Address",
    fieldType: "textarea",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: FULL,
    maxLength: 200,
  },
  {
    id: "vdf_phone",
    key: "phoneNumbers",
    title: "Phone Numbers",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "e.g. 024 XXX XXXX",
    maxLength: 60,
  },
  {
    id: "vdf_email",
    key: "email",
    title: "Email",
    fieldType: "text",
    sectionId: "main_form",
    groupId: "insurance_policy_details",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "name@company.com",
    maxLength: 80,
    description: "Must be a valid email when provided.",
  },

  // —— Limits of Liability (2 cols) ——
  {
    id: "vdf_sum_insured",
    key: "vehicleSumInsured",
    title: "Vehicle Sum Insured",
    fieldType: "number",
    sectionId: "main_form",
    groupId: "limits_of_liability",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "0.00",
    description: "Disabled automatically when policy type is Third Party Only.",
  },
  {
    id: "vdf_tp_property",
    key: "thirdPartyPropertyDamageLimit",
    title: "Third Party Property Damage Limit",
    fieldType: "number",
    sectionId: "main_form",
    groupId: "limits_of_liability",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "0.00",
  },
  {
    id: "vdf_pa_limit",
    key: "paLimit",
    title: "PA Limit",
    fieldType: "number",
    sectionId: "main_form",
    groupId: "limits_of_liability",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "0.00",
  },
  {
    id: "vdf_tp_injury",
    key: "thirdPartyInjuryDeathLimit",
    title: "Third Party Injury / Death Limit",
    fieldType: "number",
    sectionId: "main_form",
    groupId: "limits_of_liability",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: HALF,
    placeholder: "0.00",
  },
];

export const DEFAULT_VISIBLE_FIELD_IDS_BY_SECTION = Object.fromEntries(
  VEHICLE_DOCUMENT_FORM_SECTIONS.map((section) => [
    section.id,
    VEHICLE_DOCUMENT_FORM_FIELD_CATALOG.filter((field) => field.sectionId === section.id).map(
      (field) => field.id,
    ),
  ]),
);

export const LOCKED_DEFAULT_FIELD_IDS_BY_SECTION = Object.fromEntries(
  VEHICLE_DOCUMENT_FORM_SECTIONS.map((section) => [
    section.id,
    VEHICLE_DOCUMENT_FORM_FIELD_CATALOG.filter(
      (field) => field.sectionId === section.id && field.isDefaultLocked === true,
    ).map((field) => field.id),
  ]),
);

export function getLockedDefaultFieldIds(sectionId) {
  return LOCKED_DEFAULT_FIELD_IDS_BY_SECTION[sectionId] ?? [];
}

export function withLockedDefaultFields(visibleBySection = {}) {
  const next = { ...visibleBySection };
  Object.entries(LOCKED_DEFAULT_FIELD_IDS_BY_SECTION).forEach(([sectionId, lockedIds]) => {
    const current = new Set(next[sectionId] ?? []);
    lockedIds.forEach((id) => current.add(id));
    next[sectionId] = [...current];
  });
  return next;
}
