/** Catalog of fields for vehicle registration / add-vehicle form, grouped by section. */

export const VEHICLE_REGISTRATION_FORM_SECTIONS = [
  {
    id: "details",
    label: "Details",
    description: "Identification, classification, and grouping for the vehicle.",
    columns: 2,
  },
  {
    id: "lifecycle",
    label: "Lifecycle",
    description: "Lifecycle state, condition, and meter readings.",
    columns: 2,
  },
  {
    id: "financial",
    label: "Financial",
    description: "Acquisition, purchase, and warranty details.",
    columns: 2,
  },
  {
    id: "specifications",
    label: "Specifications",
    description:
      "Technical specifications for the vehicle. Nested groups are configured on this form.",
    columns: 3,
  },
  {
    id: "maintenance",
    label: "Maintenance",
    description: "Service program assignment and manufacturer recommendations.",
    columns: 1,
  },
  {
    id: "settings",
    label: "Settings",
    description: "Telematics provider and device integration toggles.",
    columns: 4,
  },
];

/**
 * Flat catalog for non-spec sections. Specs are seeded from the vehicle spec tree
 * under the Specifications Level-1 node.
 */
export const VEHICLE_REGISTRATION_FORM_FIELD_CATALOG = [
  // —— Details › Identification & Classification ——
  {
    id: "vrf_vehicle_name",
    key: "name",
    title: "Vehicle Name",
    fieldType: "text",
    sectionId: "details",
    group: "Identification & Classification",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: 2,
    placeholder: "e.g. Truck 01 or Service Van",
  },
  {
    id: "vrf_vin",
    key: "vin",
    title: "VIN/SN",
    fieldType: "text",
    sectionId: "details",
    group: "Identification & Classification",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    placeholder: "Vehicle Identification Number",
  },
  {
    id: "vrf_license_plate",
    key: "licensePlate",
    title: "Registration Number (License Plate)",
    fieldType: "text",
    sectionId: "details",
    group: "Identification & Classification",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    placeholder: "ABC-1234",
  },
  {
    id: "vrf_make",
    key: "makeId",
    title: "Make",
    fieldType: "select",
    sectionId: "details",
    group: "Identification & Classification",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    options: [],
    placeholder: "Select Make",
  },
  {
    id: "vrf_model",
    key: "modelId",
    title: "Model",
    fieldType: "select",
    sectionId: "details",
    group: "Identification & Classification",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    options: [],
    placeholder: "Select Model",
  },
  {
    id: "vrf_year",
    key: "year",
    title: "Year",
    fieldType: "number",
    sectionId: "details",
    group: "Identification & Classification",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    placeholder: "2024",
  },
  {
    id: "vrf_body_type",
    key: "bodyTypeId",
    title: "Body Type",
    fieldType: "select",
    sectionId: "details",
    group: "Identification & Classification",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    options: [],
    placeholder: "Select body type…",
  },
  {
    id: "vrf_trim",
    key: "trimId",
    title: "Trim",
    fieldType: "select",
    sectionId: "details",
    group: "Identification & Classification",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    options: [],
    placeholder: "Select trim…",
  },
  {
    id: "vrf_color",
    key: "color",
    title: "Color",
    fieldType: "text",
    sectionId: "details",
    group: "Identification & Classification",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    placeholder: "e.g. Frozen White",
  },
  {
    id: "vrf_asset_tag",
    key: "assetTag",
    title: "Asset Tag",
    fieldType: "text",
    sectionId: "details",
    group: "Identification & Classification",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    placeholder: "e.g. AST-001",
  },

  // —— Details › Grouping & Assignment ——
  {
    id: "vrf_branch",
    key: "branch",
    title: "Branch",
    fieldType: "select",
    sectionId: "details",
    group: "Grouping & Assignment",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    options: [
      { value: "33333333-3333-3333-3333-333333333333", label: "Headquarters (HQ)" },
      { value: "33333333-3333-3333-3333-333333333334", label: "North Region" },
      { value: "33333333-3333-3333-3333-333333333335", label: "South Region" },
    ],
    placeholder: "Select Branch",
  },
  {
    id: "vrf_department",
    key: "department",
    title: "Department",
    fieldType: "select",
    sectionId: "details",
    group: "Grouping & Assignment",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    options: [
      { value: "44444444-4444-4444-4444-444444444444", label: "Operations" },
      { value: "44444444-4444-4444-4444-444444444445", label: "Sales" },
      { value: "44444444-4444-4444-4444-444444444446", label: "Maintenance" },
    ],
    placeholder: "Select Department",
  },

  // —— Lifecycle ——
  {
    id: "vrf_lifecycle_state",
    key: "lifecycleState",
    title: "Lifecycle State",
    fieldType: "select",
    sectionId: "lifecycle",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: 2,
    options: [
      { value: "ORDERED", label: "Ordered" },
      { value: "RECEIVED", label: "Received" },
      { value: "ACTIVE", label: "Active" },
      { value: "RETIRED", label: "Retired" },
      { value: "SOLD", label: "Sold" },
    ],
    defaultValue: "ACTIVE",
    placeholder: "Select lifecycle state",
  },
  {
    id: "vrf_vehicle_condition",
    key: "vehicleCondition",
    title: "Vehicle Condition",
    fieldType: "select",
    sectionId: "lifecycle",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    colSpan: 2,
    options: [
      { value: "NEW", label: "New" },
      { value: "OLD", label: "Old" },
    ],
    defaultValue: "NEW",
    placeholder: "Select condition",
  },
  {
    id: "vrf_primary_meter",
    key: "primaryMeter",
    title: "Primary Meter",
    fieldType: "select",
    sectionId: "lifecycle",
    required: false,
    isActive: true,
    options: [
      { value: "ODOMETER", label: "Odometer" },
      { value: "HOUR_METER", label: "Hour Meter" },
    ],
    defaultValue: "ODOMETER",
    placeholder: "Select meter type",
  },
  {
    id: "vrf_current_mileage",
    key: "currentMileage",
    title: "Current Mileage",
    fieldType: "number",
    sectionId: "lifecycle",
    required: false,
    isActive: true,
    placeholder: "0",
  },
  {
    id: "vrf_expected_lifecycle",
    key: "expectedLifecycle",
    title: "Expected Life Cycle",
    fieldType: "number",
    sectionId: "lifecycle",
    required: false,
    isActive: true,
    placeholder: "8",
  },

  // —— Financial ——
  {
    id: "vrf_acquisition_date",
    key: "acquisitionDate",
    title: "Acquisition Date",
    fieldType: "date",
    sectionId: "financial",
    required: false,
    isActive: true,
  },
  {
    id: "vrf_purchase_type",
    key: "purchaseType",
    title: "Purchase Type",
    fieldType: "select",
    sectionId: "financial",
    required: false,
    isActive: true,
    options: [
      { value: "PURCHASE", label: "Purchase" },
      { value: "LEASE", label: "Lease" },
      { value: "FINANCE", label: "Finance" },
      { value: "THIRD_PARTY", label: "Third Party" },
    ],
    defaultValue: "PURCHASE",
    placeholder: "Select purchase type",
  },
  {
    id: "vrf_purchase_price",
    key: "purchasePrice",
    title: "Purchase Cost",
    fieldType: "number",
    sectionId: "financial",
    required: false,
    isActive: true,
    placeholder: "0.00",
  },
  {
    id: "vrf_po_number",
    key: "poNumber",
    title: "PO Number",
    fieldType: "text",
    sectionId: "financial",
    required: false,
    isActive: true,
    placeholder: "e.g. PO-8821",
  },
  {
    id: "vrf_po_date",
    key: "poDate",
    title: "PO Date",
    fieldType: "date",
    sectionId: "financial",
    required: false,
    isActive: true,
  },
  {
    id: "vrf_vendor",
    key: "vendor",
    title: "Vendor",
    fieldType: "text",
    sectionId: "financial",
    required: false,
    isActive: true,
    placeholder: "e.g. Ford North Austin",
  },
  {
    id: "vrf_warranty_info",
    key: "warrantyInfo",
    title: "Warranty Info",
    fieldType: "text",
    sectionId: "financial",
    required: false,
    isActive: true,
    placeholder: "e.g. 3yr/36,000mi",
  },
  {
    id: "vrf_residual_value",
    key: "residualValue",
    title: "Residual Value",
    fieldType: "number",
    sectionId: "financial",
    required: false,
    isActive: true,
    placeholder: "0.00",
  },

  // —— Maintenance ——
  {
    id: "vrf_maintenance_mode",
    key: "maintenanceMode",
    title: "Maintenance Source",
    fieldType: "select",
    sectionId: "maintenance",
    required: true,
    isDefaultLocked: true,
    isActive: true,
    options: [
      { value: "program", label: "Service Program" },
      { value: "manufacturer", label: "Manufacturer Recommendation" },
    ],
    defaultValue: "program",
    placeholder: "Select maintenance source",
  },
  {
    id: "vrf_service_program",
    key: "serviceProgramId",
    title: "Assign Service Program",
    fieldType: "select",
    sectionId: "maintenance",
    required: false,
    isActive: true,
    options: [],
    placeholder: "Select Service Program",
    description:
      "Assigning a program will automatically generate future service reminders based on mileage and time.",
  },

  // —— Settings ——
  {
    id: "vrf_telematics_provider",
    key: "telematicsProvider",
    title: "Telematics Provider",
    fieldType: "select",
    sectionId: "settings",
    group: "Device Integrations",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    colSpan: 4,
    options: [
      { value: "GEOTAB", label: "Geotab" },
      { value: "SAMSARA", label: "Samsara" },
    ],
    placeholder: "None configured",
  },
  {
    id: "vrf_gps_tracking",
    key: "gpsTracking",
    title: "GPS Tracking",
    fieldType: "checkbox",
    sectionId: "settings",
    group: "Device Integrations",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    defaultValue: true,
  },
  {
    id: "vrf_fuel_integration",
    key: "fuelIntegration",
    title: "Fuel Integration",
    fieldType: "checkbox",
    sectionId: "settings",
    group: "Device Integrations",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    defaultValue: true,
  },
  {
    id: "vrf_geofencing",
    key: "geofencing",
    title: "Geofencing",
    fieldType: "checkbox",
    sectionId: "settings",
    group: "Device Integrations",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    defaultValue: false,
  },
  {
    id: "vrf_diagnostics",
    key: "diagnostics",
    title: "Diagnostics",
    fieldType: "checkbox",
    sectionId: "settings",
    group: "Device Integrations",
    required: false,
    isDefaultLocked: true,
    isActive: true,
    defaultValue: false,
  },
];

/** Default-visible field ids by section (all seeded fields start visible). */
export const DEFAULT_VISIBLE_FIELD_IDS_BY_SECTION = Object.fromEntries(
  VEHICLE_REGISTRATION_FORM_SECTIONS.map((section) => [
    section.id,
    VEHICLE_REGISTRATION_FORM_FIELD_CATALOG.filter(
      (field) => field.sectionId === section.id && field.isActive !== false,
    ).map((field) => field.id),
  ]),
);

export const LOCKED_DEFAULT_FIELD_IDS_BY_SECTION = Object.fromEntries(
  VEHICLE_REGISTRATION_FORM_SECTIONS.map((section) => [
    section.id,
    VEHICLE_REGISTRATION_FORM_FIELD_CATALOG.filter(
      (field) =>
        field.sectionId === section.id && field.isDefaultLocked === true,
    ).map((field) => field.id),
  ]),
);

export function getLockedDefaultFieldIds(sectionId) {
  return LOCKED_DEFAULT_FIELD_IDS_BY_SECTION[sectionId] ?? [];
}

export function withLockedDefaultFields(visibleBySection = {}) {
  const next = { ...visibleBySection };
  Object.entries(LOCKED_DEFAULT_FIELD_IDS_BY_SECTION).forEach(
    ([sectionId, lockedIds]) => {
      const current = new Set(next[sectionId] ?? []);
      lockedIds.forEach((id) => current.add(id));
      next[sectionId] = [...current];
    },
  );
  return next;
}
