/** Store-side audit trail events (activity log for the store dashboard). */

export const AUDIT_PAGE_SIZE = 10;

export const AUDIT_MODULE_FILTERS = [
  { value: "ALL", label: "All Modules" },
  { value: "Inventory", label: "Inventory" },
  { value: "Supplies", label: "Supplies" },
  { value: "Transfers", label: "Transfers" },
  { value: "Requests", label: "Requests" },
  { value: "Approvals", label: "Approvals" },
  { value: "Setups", label: "Setups" },
  { value: "Settings", label: "Settings" },
];

export const AUDIT_ACTION_FILTERS = [
  { value: "ALL", label: "All Actions" },
  { value: "Created", label: "Created" },
  { value: "Updated", label: "Updated" },
  { value: "Deleted", label: "Deleted" },
  { value: "Approved", label: "Approved" },
  { value: "Rejected", label: "Rejected" },
  { value: "Status Change", label: "Status Change" },
  { value: "Exported", label: "Exported" },
  { value: "Login", label: "Login" },
];

export const AUDIT_EVENTS = [
  {
    id: "aud-001",
    at: "2026-08-21T14:22:00",
    actor: "Ama Serwaa",
    actorEmail: "ama.serwaa@stores.local",
    action: "Approved",
    module: "Approvals",
    target: "REQ-ACC-2026-014 · Floor Mat Set (Universal)",
    summary: "Approved supply request for 4 Floor Mat Sets across Accra Central and Tema Fleet stores.",
    ipAddress: "41.66.210.18",
    source: "Web",
    changes: [
      { field: "Status", before: "Pending", after: "Approved" },
      { field: "Approver comment", before: "—", after: "Issue from Accra and Tema allocations" },
    ],
  },
  {
    id: "aud-002",
    at: "2026-08-21T13:05:00",
    actor: "Kwesi Mensah",
    actorEmail: "kwesi.mensah@stores.local",
    action: "Created",
    module: "Inventory",
    target: "ACC-WIP-014 · Wiper Blade Pair 22\"",
    summary: "Recorded a new accessory receipt at Tema Fleet Store.",
    ipAddress: "41.66.210.42",
    source: "Web",
    changes: [
      { field: "Item code", before: "—", after: "ACC-WIP-014" },
      { field: "Quantity", before: "—", after: "24" },
      { field: "Store", before: "—", after: "Tema Fleet Store — Community 12" },
    ],
  },
  {
    id: "aud-003",
    at: "2026-08-21T11:48:00",
    actor: "Selorm Gbeho",
    actorEmail: "selorm.gbeho@stores.local",
    action: "Status Change",
    module: "Transfers",
    target: "IST-ACC-2026-001 · Floor Mat Set (Universal)",
    summary: "Dispatched inter-store transfer from Accra Central to Tema Fleet Store.",
    ipAddress: "102.176.88.55",
    source: "Web",
    changes: [
      { field: "Status", before: "Pending", after: "In Transit" },
      { field: "Dispatcher", before: "—", after: "Selorm Gbeho" },
    ],
  },
  {
    id: "aud-004",
    at: "2026-08-21T10:15:00",
    actor: "Esi Nyarko",
    actorEmail: "esi.nyarko@stores.local",
    action: "Created",
    module: "Requests",
    target: "REQ-ACC-2026-024 · Fire Extinguisher 2kg",
    summary: "Raised a request from stores for 6 fire extinguishers at Accra Central Store.",
    ipAddress: "154.160.22.9",
    source: "Web",
    changes: [
      { field: "Item", before: "—", after: "Fire Extinguisher 2kg" },
      { field: "Quantity", before: "—", after: "6" },
      { field: "Store", before: "—", after: "Accra Central Store — Ringway Estates" },
    ],
  },
  {
    id: "aud-005",
    at: "2026-08-21T09:02:00",
    actor: "Store Administrator",
    actorEmail: "admin@stores.local",
    action: "Updated",
    module: "Setups",
    target: "Stores · Kumasi Regional Store",
    summary: "Updated the Kumasi Regional Store phone number and manager contact.",
    ipAddress: "41.66.210.18",
    source: "Web",
    changes: [
      { field: "Phone", before: "032 202 3300", after: "032 202 3340" },
      { field: "Manager", before: "Kojo Owusu", after: "Yaw Mensah" },
    ],
  },
  {
    id: "aud-006",
    at: "2026-08-20T17:40:00",
    actor: "Yaw Mensah",
    actorEmail: "yaw.mensah@stores.local",
    action: "Created",
    module: "Supplies",
    target: "REQ-ACC-2026-018 · Jump Starter Pack",
    summary: "Created a supply requisition for 3 jump starter packs at Kumasi Regional Store.",
    ipAddress: "41.66.211.03",
    source: "Web",
    changes: [
      { field: "Item", before: "—", after: "Jump Starter Pack" },
      { field: "Quantity", before: "—", after: "3" },
      { field: "Receiver", before: "—", after: "Adjei Boateng" },
    ],
  },
  {
    id: "aud-007",
    at: "2026-08-20T16:12:00",
    actor: "Ama Serwaa",
    actorEmail: "ama.serwaa@stores.local",
    action: "Rejected",
    module: "Approvals",
    target: "IST-ACC-2026-007 · USB Dual Car Charger",
    summary: "Rejected inter-store transfer — destination store already holds surplus chargers.",
    ipAddress: "41.66.210.18",
    source: "Web",
    changes: [
      { field: "Status", before: "Pending Approval", after: "Rejected" },
      { field: "Comment", before: "—", after: "Tema already has surplus USB chargers" },
    ],
  },
  {
    id: "aud-008",
    at: "2026-08-20T14:55:00",
    actor: "Kofi Ansah",
    actorEmail: "kofi.ansah@stores.local",
    action: "Updated",
    module: "Inventory",
    target: "ACC-TRI-021 · Warning Triangle Kit",
    summary: "Updated shelf position after a store layout change at Tema Fleet Store.",
    ipAddress: "41.66.210.42",
    source: "Web",
    changes: [
      { field: "Shelf / position", before: "Aisle C · Shelf A1", after: "Aisle B · Shelf C3" },
      { field: "On-hand qty", before: "12", after: "12" },
    ],
  },
  {
    id: "aud-009",
    at: "2026-08-20T12:30:00",
    actor: "Ama Serwaa",
    actorEmail: "ama.serwaa@stores.local",
    action: "Created",
    module: "Transfers",
    target: "IST-ACC-2026-002 · Fire Extinguisher 2kg",
    summary: "Requested transfer of 8 fire extinguishers from Accra Central to Takoradi Regional Store.",
    ipAddress: "41.66.210.18",
    source: "Web",
    changes: [
      { field: "From store", before: "—", after: "Accra Central Store — Ringway Estates" },
      { field: "To store", before: "—", after: "Takoradi Regional Store — Effia" },
      { field: "Quantity", before: "—", after: "8" },
    ],
  },
  {
    id: "aud-010",
    at: "2026-08-20T09:18:00",
    actor: "System",
    actorEmail: "system@stores.local",
    action: "Exported",
    module: "Inventory",
    target: "Accessory stock ledger",
    summary: "Inventory ledger export generated by Ama Serwaa.",
    ipAddress: "41.66.210.18",
    source: "Web",
    changes: [
      { field: "Export format", before: "—", after: "CSV" },
      { field: "Date range", before: "—", after: "Jul 2026" },
    ],
  },
  {
    id: "aud-011",
    at: "2026-08-19T18:05:00",
    actor: "Store Administrator",
    actorEmail: "admin@stores.local",
    action: "Deleted",
    module: "Setups",
    target: "Suppliers · Golden Lube Ghana",
    summary: "Removed an inactive lubricant supplier that is no longer used for accessory receipts.",
    ipAddress: "41.66.210.18",
    source: "Web",
    changes: [
      { field: "Supplier", before: "Golden Lube Ghana", after: "Removed" },
    ],
  },
  {
    id: "aud-012",
    at: "2026-08-19T15:40:00",
    actor: "Store Administrator",
    actorEmail: "admin@stores.local",
    action: "Updated",
    module: "Settings",
    target: "User Roles · Store Manager",
    summary: "Granted view access to Audit Trail for the Store Manager role.",
    ipAddress: "41.66.210.18",
    source: "Web",
    changes: [
      { field: "Permission", before: "auditAccess: none", after: "auditAccess: view" },
    ],
  },
  {
    id: "aud-013",
    at: "2026-08-19T08:01:00",
    actor: "Esi Nyarko",
    actorEmail: "esi.nyarko@stores.local",
    action: "Login",
    module: "Settings",
    target: "Session started",
    summary: "Successful sign-in from Accra Central Store network.",
    ipAddress: "154.160.22.9",
    source: "Web",
    changes: [],
  },
  {
    id: "aud-014",
    at: "2026-08-18T16:28:00",
    actor: "Akosua Boateng",
    actorEmail: "akosua.boateng@stores.local",
    action: "Status Change",
    module: "Supplies",
    target: "REQ-ACC-2026-015 · High-visibility vest",
    summary: "Issued 10 high-visibility vests to Fiifi Bentum at Takoradi Regional Store.",
    ipAddress: "102.176.88.55",
    source: "Web",
    changes: [
      { field: "Status", before: "Pending Issuance", after: "Supplied" },
      { field: "Issued qty", before: "0", after: "10" },
      { field: "Receiver", before: "—", after: "Fiifi Bentum" },
    ],
  },
  {
    id: "aud-015",
    at: "2026-08-18T11:10:00",
    actor: "Kwesi Mensah",
    actorEmail: "kwesi.mensah@stores.local",
    action: "Created",
    module: "Setups",
    target: "Users · Nana Osei",
    summary: "Added Nana Osei as staff at Accra Central Store.",
    ipAddress: "41.66.210.42",
    source: "Web",
    changes: [
      { field: "Role", before: "—", after: "Staff" },
      { field: "Store", before: "—", after: "Accra Central Store — Ringway Estates" },
      { field: "Status", before: "—", after: "Active" },
    ],
  },
  {
    id: "aud-016",
    at: "2026-08-17T14:44:00",
    actor: "Ibrahim Fuseini",
    actorEmail: "ibrahim.fuseini@stores.local",
    action: "Updated",
    module: "Inventory",
    target: "ACC-FIR-008 · Fire Extinguisher 2kg",
    summary: "Approved inbound stock receipt of 12 fire extinguishers at Tamale Regional Store.",
    ipAddress: "41.66.212.11",
    source: "Web",
    changes: [
      { field: "Receipt status", before: "Pending approval", after: "Approved" },
      { field: "On-hand qty", before: "4", after: "16" },
    ],
  },
];

export function formatAuditWhen(iso) {
  if (!iso) return "—";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return date.toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function getAuditEvents() {
  return AUDIT_EVENTS.map((row) => ({ ...row, changes: [...(row.changes ?? [])] }));
}
